### ISSUE TITLE
sqlite3.DatabaseError: authorization denied (knowledgeC.db protected somehow)

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-import-screentime#8]
Getting this whenever I try to open the file.

```
Reading from database file at /Users/erb/Library/Application Support/Knowledge/knowledgeC.db
Traceback (most recent call last):
  File "/Users/erb/Programming/activitywatch/other/aw-import-screentime/main.py", line 114, in <module>
    main()
  File "/Users/erb/Programming/activitywatch/other/aw-import-screentime/main.py", line 12, in main
    conn = sqlite3.connect(_get_db_path())
sqlite3.DatabaseError: authorization denied
```

Some investigation...

```
$ ls -l /Users/erb/Library/Application Support/Knowledge/knowledgeC.db
-rw-r--r-- 1 erb staff 1.4M Feb 22 11:22 '/Users/erb/Library/Application Support/Knowledge/knowledgeC.db'

$ sudo cp '/Users/erb/Library/Application Support/Knowledge/knowledgeC.db' .
cp: cannot open '/Users/erb/Library/Application Support/Knowledge/knowledgeC.db' for reading: Operation not permitted
```

Not sure what's up, input appreciated.

**Comment by ErikBjare** [comment]
Apparently had to give my terminal "Full Disk Access":

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1405370/221242660-9d2da652-3d20-4356-a691-c3f1aa31032d.png">
